version: "3.8"

name: todo-app

services:
  todo-app:
    build:
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "8000:8000"
    command:
    volumes:
      - .:/app
    depends_on:
      - postgres
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: todo-app-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16-alpine
    container_name: todo-app-postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: todo-app-redis
    ports:
      - "6379:6379"
