"""empty message

Revision ID: 1c68af5d9fd7
Revises: 42000d0fc6dc
Create Date: 2024-09-17 20:16:17.021081

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1c68af5d9fd7'
down_revision = '42000d0fc6dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priorities', sa.Column('value', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('priorities', 'value')
    # ### end Alembic commands ###
