"""empty message

Revision ID: 42000d0fc6dc
Revises: db71c6fa629e
Create Date: 2024-09-15 01:37:00.161256

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42000d0fc6dc'
down_revision = 'db71c6fa629e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'priority_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
